// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define READER_FONT_ID (-1667320299)
#define UI_10_FONT_ID (-381091506)
#define UI_12_FONT_ID (-2011443791)
#define SMALL_FONT_ID (1197804093)
